name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "Syamala@2102" | docker login -u "syamaladuddugalla" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t syamaladuddugalla/test-deploy-eks-app:latest .

      - name: Push Docker image
        run: |
          docker push syamaladuddugalla/test-deploy-eks-app:latest
